<template>
  <Visitor
    access="delivery_access"
    view="delivery_view"
    create="delivery_create"
    edit="delivery_edit"
    delete="delivery_delete"
    visitor_type="contractor"
    label="Contractor"
  />
</template>